name_collector/urls.py
from django.urls import path

from . import views

app_name = 'name_collector'
urlpatterns = [
    path('', views.index, name='index'),
    path('userlist/', views.userlist, name='userlist')
]

name_storage/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('name_collector/', include('name_collector.urls')),
    path('admin/', admin.site.urls),
]

name_collector/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'Users'

name_collector/views.py
from django.shortcuts import render

from name_collector.models import User


def index(request):
    message = ''
    if request.method == "POST":
        u = User(name=request.POST.get("name"))
        if u.name in tuple(i.name for i in User.objects.all()):
            message = f'Уже виделись, {u.name}'
        else:
            message = f'Привет, {u.name}'
            u.save()
    return render(request, "name_collector/index.html", {"message": message})


def userlist(request):
    users = User.objects.all()
    return render(request, "name_collector/userlist.html", {"users": users})

name_collector/templates/name_collector/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Форма приветствия</title>
</head>
<body class="container">
    <form method="POST" action="{% url 'name_collector:index' %}">
        {% csrf_token %}
        <p>
            <label>Введите имя</label><br>
            <input type="text" name="name" />
        </p>
        <input type="submit" value="Сохранить" >
        {% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
    </form>
    <br>
    <a href="{% url 'name_collector:userlist' %}">User list</a>
</body>
</html>

name_collector/templates/name_collector/userlist.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Список всех имён</title>
</head>
<body class="container">
    {% if users.count > 0 %}
    <h3>Список пользователей</h3>
    <table>
        <tr><th>Id</th><th>Имя</th></tr>
        {% for user in users %}
        <tr><td>{{ user.id }}</td><td>{{ user.name }}</td></tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>